- name: "Install Nginx packages"
  apt: 
    name: nginx 
    state: present
  tags: installation

- name: "Ensure nginx is running"
  shell: service nginx status
  register: service_status
- debug:
    var: service_status.stdout_lines
    

